const express = require('express')
const ipMiddleware = require('./Location/ipMiddleware')
const location = require('./Location/location')
require('dotenv').config()
const cors = require('cors')
const bodyParser = require('body-parser')
const { default: axios } = require('axios')
const port = process.env.port || 8080
const app = express() 
app.use(cors({origin:'*', credentials:"true"}))
app.use(bodyParser.json())
app.use(express.static('public'))
app.get('/', async(req, res) => await axios({url:'https://ipapi.co/json', method:'GET', headers:{"Content-Type":"application/json"}}).then(res => res.status(200).send(res.data)).catch(err => res.status(400).send(err)))
app.get('/location', ipMiddleware, location)
app.listen(port, ()=>console.log(`The server is running at http://localhost:${port}`))