const express = require('express')
const ipMiddleware = require('./Location/ipMiddleware')
const location = require('./Location/location')
require('dotenv').config()
const cors = require('cors')
const bodyParser = require('body-parser')
const port = process.env.port || 8080
const app = express() 
app.use(cors({origin:'*', credentials:"true"}))
app.use(bodyParser.json())
app.use(express.static('public'))
app.get('/', async(req, res) => res.status(200).send('The api is working normally.'))
app.get('/location', ipMiddleware, location)
app.listen(port, ()=>console.log(`The server is running at http://localhost:${port}`))